version: "3.5"
services:

  alertmanager-adapter:
    image: alertmanager-adapter
    container_name: alertmanager-adapter
    environment:
      SERVER_PORT: "8080"
      JAVA_OPTS: "-Xmx256m"
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_BOTUSERNAME: ${TELEGRAM_BOTUSERNAME}
      TELEGRAM_CHATID: ${TELEGRAM_CHATID}
    ports:
      - "8090:8080"