## Telegram integration properties
telegram:
  baseUrl: https://api.telegram.org/bot
  token:
  botUserName: EcaServiceBot
  chatId: 1480287278
  numThreads: 3
  alertBatchSize: 5

## Swagger properties
open-api:
  basePath: /
  title: Service for sending alerts from alertmanager to telegram
  description: Service implements alertmanager adapter for recieving alert requests from alertmanager for sending to telegram
  author: Roman Batygin
  email: roman.batygin@mail.ru
  projectVersion: @project.version@
